spring.application.name=Medi_Care_v1
server.port=8080


debug=false
spring.datasource.url=jdbc:postgresql://localhost:5432/medi_care

spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



#profiles
spring.profiles.active=dev

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true